FROM alpine

#RUN apk -q --update add wget tar xz
RUN apk -q --update add nodejs

ENV APPDIR /APP

WORKDIR ${APP}

#RUN wget --no-check-certificate --quiet https://nodejs.org/dist/v4.4.4/node-v4.4.4-linux-x64.tar.xz -O /tmp/node.tar.xz  && \
#tar -Jxf /tmp/node.tar.xz --strip-components=1 >/dev/null 2>&1
 
ADD simpleapp.js simpleapp.js
ADD package.json package.json

#ENV PATH $PATH:/${APPDIR}/bin

RUN npm install 

CMD ["node","simpleapp.js","3000"]

EXPOSE 3000
